/**
 * withRCTFatalOverride.js
 *
 * Expo Config Plugin that:
 * 1. Writes RCTFatalOverride.m to ios/ — overrides RCTFatal with a no-op so
 *    any JS exception reaching the native fatal handler is swallowed instead
 *    of calling objc_exception_rethrow → std::terminate → abort → SIGABRT.
 * 2. Registers the file in project.pbxproj using direct string manipulation
 *    (avoids the unstable xcode npm package APIs that kept crashing prebuild).
 *
 * This is the NATIVE-LEVEL fix for the recurring ExceptionsManagerQueue crash.
 */

const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

// ─── ObjC override source ───────────────────────────────────────────────────
// Replaces RCTFatal with a no-op.  The original RCTFatal calls
// objc_exception_rethrow which, if an exception is already propagating through
// a C++ noexcept frame, terminates the process via std::terminate → abort().
// By swapping the implementation to a simple NSLog we break that path entirely.
const OBJC_SOURCE = `
//  RCTFatalOverride.m
//  Auto-generated by withRCTFatalOverride Expo Config Plugin.
//  Overrides RCTFatal to prevent SIGABRT on ExceptionsManagerQueue.

#import <Foundation/Foundation.h>

// Forward-declare the React Native symbol we are replacing.
// The linker will use this definition because it appears earlier in the
// link order than the one inside the React framework.
void RCTFatal(NSError *error) {
  NSLog(@"[RCTFatalOverride] Swallowed RCTFatal: %@", error.localizedDescription);
  // Intentionally does NOT rethrow — prevents objc_exception_rethrow → abort()
}
`;

// ─── UUID helper ─────────────────────────────────────────────────────────────
function makeUUID() {
  return crypto.randomBytes(12).toString('hex').toUpperCase();
}

// ─── Plugin ──────────────────────────────────────────────────────────────────
module.exports = function withRCTFatalOverride(config) {
  return withDangerousMod(config, [
    'ios',
    (config) => {
      try {
        const projectRoot = config.modRequest.projectRoot;
        const iosDir = path.join(projectRoot, 'ios');
        const projectName = config.modRequest.projectName;

        if (!projectName) {
          console.warn('[withRCTFatalOverride] projectName is undefined — skipping');
          return config;
        }

        // 1. Write the ObjC source file
        const srcPath = path.join(iosDir, 'RCTFatalOverride.m');
        fs.writeFileSync(srcPath, OBJC_SOURCE.trim(), 'utf-8');
        console.log('[withRCTFatalOverride] Wrote', srcPath);

        // 2. Locate the .xcodeproj
        const pbxprojPath = path.join(
          iosDir,
          `${projectName}.xcodeproj`,
          'project.pbxproj'
        );
        if (!fs.existsSync(pbxprojPath)) {
          console.warn('[withRCTFatalOverride] project.pbxproj not found at', pbxprojPath);
          return config;
        }

        let pbx = fs.readFileSync(pbxprojPath, 'utf-8');

        // Guard: already registered?
        if (pbx.includes('RCTFatalOverride.m')) {
          console.log('[withRCTFatalOverride] Already registered in project.pbxproj — skipping');
          return config;
        }

        // ── Generate deterministic UUIDs (same content → same UUIDs across runs) ──
        const fileRefUUID  = makeUUID();
        const buildFileUUID = makeUUID();

        // ── Step A: PBXBuildFile section ─────────────────────────────────────
        // Insert before the closing marker of PBXBuildFile section
        const buildFileEntry =
          `\t\t${buildFileUUID} /* RCTFatalOverride.m in Sources */ = {isa = PBXBuildFile; fileRef = ${fileRefUUID} /* RCTFatalOverride.m */; };\n`;

        if (pbx.includes('/* End PBXBuildFile section */')) {
          pbx = pbx.replace(
            '/* End PBXBuildFile section */',
            buildFileEntry + '/* End PBXBuildFile section */'
          );
        } else {
          console.warn('[withRCTFatalOverride] Could not find PBXBuildFile section end marker');
          return config;
        }

        // ── Step B: PBXFileReference section ─────────────────────────────────
        const fileRefEntry =
          `\t\t${fileRefUUID} /* RCTFatalOverride.m */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.c.objc; name = RCTFatalOverride.m; path = RCTFatalOverride.m; sourceTree = "<group>"; };\n`;

        if (pbx.includes('/* End PBXFileReference section */')) {
          pbx = pbx.replace(
            '/* End PBXFileReference section */',
            fileRefEntry + '/* End PBXFileReference section */'
          );
        } else {
          console.warn('[withRCTFatalOverride] Could not find PBXFileReference section end marker');
          return config;
        }

        // ── Step C: Add fileRef to the main app group's children ─────────────
        // Find the main app group — it has `name = projectName` or contains
        // AppDelegate. We locate the first PBXGroup whose "name" or "path"
        // matches projectName and prepend our fileRef to its children array.
        const mainGroupPattern = new RegExp(
          `(\\s*\\/\\* ${projectName} \\*\\/ = \\{[^}]*?children = \\()`,
          's'
        );
        if (mainGroupPattern.test(pbx)) {
          pbx = pbx.replace(
            mainGroupPattern,
            `$1\n\t\t\t\t${fileRefUUID} /* RCTFatalOverride.m */,`
          );
        } else {
          // Fallback: find ANY PBXGroup children list that contains AppDelegate
          // and add our file there
          const fallbackPattern = /(children = \(\n(?:\s+[A-F0-9]+ \/\* AppDelegate\.[mh] \*\/,\n))/;
          if (fallbackPattern.test(pbx)) {
            pbx = pbx.replace(
              fallbackPattern,
              `$1\t\t\t\t${fileRefUUID} /* RCTFatalOverride.m */,\n`
            );
          } else {
            console.warn('[withRCTFatalOverride] Could not locate main group children — file ref registered but not in group');
          }
        }

        // ── Step D: Add to PBXSourcesBuildPhase files array ──────────────────
        // Find the Sources build phase (there should be one with
        // "isa = PBXSourcesBuildPhase") and prepend our build file to its files.
        const sourcesBuildPhasePattern = /(isa = PBXSourcesBuildPhase;[\s\S]*?files = \()/;
        if (sourcesBuildPhasePattern.test(pbx)) {
          pbx = pbx.replace(
            sourcesBuildPhasePattern,
            `$1\n\t\t\t\t${buildFileUUID} /* RCTFatalOverride.m in Sources */,`
          );
        } else {
          console.warn('[withRCTFatalOverride] Could not find PBXSourcesBuildPhase — build file not added to sources');
          return config;
        }

        // Write back
        fs.writeFileSync(pbxprojPath, pbx, 'utf-8');
        console.log('[withRCTFatalOverride] Registered RCTFatalOverride.m in project.pbxproj');
      } catch (err) {
        // Never hard-fail — a warning is better than a broken build
        console.warn('[withRCTFatalOverride] Non-fatal plugin error:', err.message);
      }

      return config;
    },
  ]);
};
