/**
 * Support Page — /support
 * Apple App Store requirement: contact email, FAQ, privacy policy link.
 */

import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  Pressable,
  Linking,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { MaterialIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useTheme } from '@/contexts/ThemeContext';
import { Spacing, Radius, Typography } from '@/constants/theme';

const SUPPORT_EMAIL = 'support@kairosdigitallabs.com';
const APP_NAME = 'MyMoodMapp';

const FAQ_ITEMS = [
  {
    q: 'How do I cancel my subscription?',
    a: 'On iOS: Open the Settings app → tap your Apple ID → Subscriptions → MyMoodMapp → Cancel Subscription.\n\nOn Android: Open Google Play → Menu → Subscriptions → MyMoodMapp → Cancel.\n\nOn web: Go to the Me tab → tap Manage next to your subscription → Cancel in the billing portal.\n\nYou retain access until the end of your billing period.',
  },
  {
    q: 'How does the 30-day free trial work?',
    a: 'When you start a Pro or Therapist Pro trial, you get full access for 30 days at no cost. On web, no credit card is required — you add one if you choose to continue after day 30. On iOS and Android, your App Store or Google Play payment method is charged automatically on day 31 unless you cancel before then.',
  },
  {
    q: 'Can I restore my purchases on a new device?',
    a: 'Yes. On iOS or Android, go to the Me tab → scroll to the upgrade section → tap Restore purchases. This restores any active subscription tied to your Apple ID or Google account.',
  },
  {
    q: 'Is my mood data private and secure?',
    a: 'Yes. All your data is encrypted in transit and at rest. We never sell or share your personal data with third parties. You can export or delete your data at any time from the Me tab. See our full Privacy Policy for details.',
  },
  {
    q: 'Why is my health data not showing on the web?',
    a: 'Health and fitness data (steps, sleep, heart rate) sync from your phone to the web app. To populate it: open the app on your iPhone or Android phone while signed in, then refresh the web dashboard. The sync requires the full iOS or Android app — not the Expo Go preview build.',
  },
  {
    q: 'How do I connect with a therapist or buddy?',
    a: 'Go to the Me tab → Accountability Buddy → Add a buddy, and enter your buddy or therapist\'s email. They will receive an invite and, once accepted, can see when you last logged.\n\nTherapists using Therapist Pro can also invite clients from their dashboard with a link.',
  },
  {
    q: 'How does the AI generate wellness reports?',
    a: 'AI reports are generated by an on-demand language model using your mood entries, fitness data, weather, cycle tracking (if enabled), and your optional Wellbeing Profile quiz results. Reports are stored in your account and never shared without your consent.',
  },
  {
    q: 'What data does MyMoodMapp access from Apple Health / Google Fit?',
    a: 'MyMoodMapp reads steps, active energy, resting heart rate, average heart rate, sleep analysis, and workout minutes. This data is only used to provide you with personalised insights inside the app. We do not write back to Apple Health or Google Fit.',
  },
  {
    q: 'How do I delete my account and data?',
    a: 'Go to Me tab → Account (tap your name at the top) → scroll down → Delete account. Your account and all data will be permanently removed within 30 days.\n\nYou can also email ' + SUPPORT_EMAIL + ' with the subject "Delete my account".',
  },
  {
    q: 'The app is not working correctly — what should I do?',
    a: 'First try: (1) Force-close and reopen the app. (2) Check your internet connection. (3) Sign out and sign back in. If the issue persists, email us at ' + SUPPORT_EMAIL + ' with a description of the problem and your device model / OS version.',
  },
];

export default function SupportScreen() {
  const { colors: C } = useTheme();
  const router = useRouter();
  const [expanded, setExpanded] = useState<number | null>(null);

  const toggle = (i: number) => setExpanded(prev => prev === i ? null : i);

  return (
    <SafeAreaView style={[s.safe, { backgroundColor: C.background }]} edges={['top']}>
      {/* Header */}
      <View style={[s.header, { borderBottomColor: C.border }]}>
        <Pressable onPress={() => router.back()} hitSlop={12} style={({ pressed }) => [s.backBtn, pressed && { opacity: 0.6 }]}>
          <MaterialIcons name="arrow-back" size={22} color={C.textPrimary} />
        </Pressable>
        <Text style={[s.headerTitle, { color: C.textPrimary }]}>Support</Text>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}>

        {/* Hero */}
        <View style={[s.hero, { backgroundColor: C.surface, borderColor: C.border }]}>
          <View style={[s.heroIcon, { backgroundColor: C.primary + '18' }]}>
            <Text style={{ fontSize: 32 }}>😌</Text>
          </View>
          <Text style={[s.heroTitle, { color: C.textPrimary }]}>How can we help?</Text>
          <Text style={[s.heroSub, { color: C.textSecondary }]}>
            We typically reply within 24 hours on business days.
          </Text>
        </View>

        {/* Contact card */}
        <View style={[s.card, { backgroundColor: C.surfaceElevated, borderColor: C.primary + '40' }]}>
          <View style={s.cardRow}>
            <View style={[s.cardIcon, { backgroundColor: C.primary + '18' }]}>
              <MaterialIcons name="email" size={20} color={C.primary} />
            </View>
            <View style={{ flex: 1 }}>
              <Text style={[s.cardLabel, { color: C.textMuted }]}>Email support</Text>
              <Text style={[s.cardValue, { color: C.textPrimary }]}>{SUPPORT_EMAIL}</Text>
            </View>
          </View>
          <Pressable
            onPress={() => Linking.openURL(`mailto:${SUPPORT_EMAIL}?subject=Support request — ${APP_NAME}`)}
            style={({ pressed }) => [s.emailBtn, { backgroundColor: C.primary }, pressed && { opacity: 0.85 }]}
          >
            <MaterialIcons name="send" size={16} color="#000" />
            <Text style={s.emailBtnText}>Send email</Text>
          </Pressable>
        </View>

        {/* Subscription support */}
        <View style={[s.card, { backgroundColor: C.surfaceElevated, borderColor: C.secondary + '40' }]}>
          <View style={s.cardRow}>
            <View style={[s.cardIcon, { backgroundColor: C.secondary + '18' }]}>
              <MaterialIcons name="credit-card" size={20} color={C.secondary} />
            </View>
            <View style={{ flex: 1 }}>
              <Text style={[s.cardLabel, { color: C.textMuted }]}>Billing & subscriptions</Text>
              <Text style={[s.cardValue, { color: C.textPrimary }]}>Cancellations, refunds, billing issues</Text>
            </View>
          </View>
          <Pressable
            onPress={() => Linking.openURL(`mailto:${SUPPORT_EMAIL}?subject=Billing support — ${APP_NAME}`)}
            style={({ pressed }) => [s.emailBtn, { backgroundColor: C.secondary }, pressed && { opacity: 0.85 }]}
          >
            <MaterialIcons name="send" size={16} color="#fff" />
            <Text style={[s.emailBtnText, { color: '#fff' }]}>Contact billing support</Text>
          </Pressable>
        </View>

        {/* Privacy & Terms links */}
        <View style={[s.linksRow, { borderColor: C.border }]}>
          <Pressable
            onPress={() => router.push('/privacy' as any)}
            style={({ pressed }) => [s.linkBtn, { borderColor: C.border, backgroundColor: C.surface }, pressed && { opacity: 0.75 }]}
          >
            <MaterialIcons name="privacy-tip" size={16} color={C.secondary} />
            <Text style={[s.linkBtnText, { color: C.secondary }]}>Privacy Policy</Text>
            <MaterialIcons name="open-in-new" size={14} color={C.textMuted} />
          </Pressable>
          <Pressable
            onPress={() => router.push('/terms' as any)}
            style={({ pressed }) => [s.linkBtn, { borderColor: C.border, backgroundColor: C.surface }, pressed && { opacity: 0.75 }]}
          >
            <MaterialIcons name="description" size={16} color={C.textMuted} />
            <Text style={[s.linkBtnText, { color: C.textMuted }]}>Terms of Service</Text>
            <MaterialIcons name="chevron-right" size={14} color={C.textMuted} />
          </Pressable>
        </View>

        {/* FAQ */}
        <Text style={[s.sectionTitle, { color: C.textMuted }]}>Frequently Asked Questions</Text>
        <View style={[s.faqContainer, { borderColor: C.border, backgroundColor: C.surfaceElevated }]}>
          {FAQ_ITEMS.map((item, i) => {
            const open = expanded === i;
            return (
              <View key={i} style={[s.faqItem, i > 0 && { borderTopWidth: 1, borderTopColor: C.border }]}>
                <Pressable
                  onPress={() => toggle(i)}
                  style={({ pressed }) => [s.faqQuestion, pressed && { opacity: 0.75 }]}
                  accessibilityRole="button"
                >
                  <Text style={[s.faqQuestionText, { color: C.textPrimary }]} numberOfLines={open ? undefined : 2}>
                    {item.q}
                  </Text>
                  <MaterialIcons
                    name={open ? 'expand-less' : 'expand-more'}
                    size={20}
                    color={C.textMuted}
                  />
                </Pressable>
                {open ? (
                  <Text style={[s.faqAnswer, { color: C.textSecondary }]}>{item.a}</Text>
                ) : null}
              </View>
            );
          })}
        </View>

        {/* Footer note */}
        <Text style={[s.footer, { color: C.textMuted }]}>
          {APP_NAME} · {SUPPORT_EMAIL}
        </Text>
        <Text style={[s.footer, { color: C.textMuted, marginTop: 2 }]}>
          © {new Date().getFullYear()} MyMoodMapp. All rights reserved.
        </Text>

      </ScrollView>
    </SafeAreaView>
  );
}

const s = StyleSheet.create({
  safe: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.md,
    paddingVertical: 14,
    borderBottomWidth: 1,
  },
  backBtn: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: Radius.full },
  headerTitle: { fontSize: Typography.fontSizes.md, fontWeight: '700', includeFontPadding: false },
  scroll: { padding: Spacing.md, paddingBottom: 60, gap: Spacing.md },

  hero: {
    alignItems: 'center',
    gap: Spacing.sm,
    padding: Spacing.lg,
    borderRadius: Radius.xl,
    borderWidth: 1,
  },
  heroIcon: { width: 64, height: 64, borderRadius: Radius.xl, alignItems: 'center', justifyContent: 'center' },
  heroTitle: { fontSize: Typography.fontSizes.lg, fontWeight: '800', includeFontPadding: false },
  heroSub: { fontSize: Typography.fontSizes.xs, textAlign: 'center', lineHeight: 20, includeFontPadding: false },

  card: {
    borderRadius: Radius.xl,
    borderWidth: 1,
    padding: Spacing.md,
    gap: Spacing.md,
  },
  cardRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md },
  cardIcon: { width: 42, height: 42, borderRadius: Radius.md, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  cardLabel: { fontSize: Typography.fontSizes.xs, includeFontPadding: false, marginBottom: 2 },
  cardValue: { fontSize: Typography.fontSizes.sm, fontWeight: '600', includeFontPadding: false },

  emailBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    borderRadius: Radius.lg,
    paddingVertical: 13,
    minHeight: 48,
  },
  emailBtnText: { fontSize: Typography.fontSizes.sm, fontWeight: '700', color: '#000', includeFontPadding: false },

  linksRow: { flexDirection: 'row', gap: Spacing.sm },
  linkBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderRadius: Radius.lg,
    borderWidth: 1,
    paddingVertical: 12,
    minHeight: 48,
  },
  linkBtnText: { fontSize: Typography.fontSizes.xs, fontWeight: '600', includeFontPadding: false },

  sectionTitle: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginTop: Spacing.sm,
    includeFontPadding: false,
  },

  faqContainer: { borderRadius: Radius.xl, borderWidth: 1, overflow: 'hidden' },
  faqItem: { paddingHorizontal: Spacing.md },
  faqQuestion: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    minHeight: 52,
  },
  faqQuestionText: { flex: 1, fontSize: Typography.fontSizes.sm, fontWeight: '600', lineHeight: 22, includeFontPadding: false },
  faqAnswer: { fontSize: Typography.fontSizes.xs, lineHeight: 22, paddingBottom: Spacing.md, includeFontPadding: false },

  footer: { fontSize: 12, textAlign: 'center', includeFontPadding: false },
});
